[package]
name = "wallet"
version = "0.5.0-pre4"
authors = ["Nicolas Di Prima <nicolas@primetype.co.uk>", "Vincent Hanquez <vincent@typed.io>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
cryptoxide = "0.2.0"
ed25519-bip32 = "^0.3.1"
cbor_event = "^2.1.3"
thiserror = { version = "1.0.13", default-features = false }
bip39 = { path = "../bip39" }
chain-path-derivation = { path = "../chain-path-derivation" }
hdkeygen = { path = "../hdkeygen" }
hex = "0.4.2"
im-rc = "15.0.0"

chain-time = { path = "../chain-deps/chain-time" }
chain-crypto = { path = "../chain-deps/chain-crypto" }
chain-addr = { path = "../chain-deps/chain-addr" }
chain-impl-mockchain = { path = "../chain-deps/chain-impl-mockchain" }
cardano-legacy-address = { path = "../chain-deps/cardano-legacy-address" }

[dev-dependencies]
quickcheck = "0.9"
quickcheck_macros = "0.9"
chain-ser = { path = "../chain-deps/chain-ser" }